name: Schedule Heroku Dynos

on:
  schedule:
    - cron: '0 9 * * *'  # Encender a las 9 AM UTC
    - cron: '0 15 * * *' # Apagar a las 3 PM UTC

jobs:
  start-dynos:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 9 * * *'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Start Heroku Dynos
        run: heroku ps:scale web=1 --app java-backend-coding-challenge
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

  stop-dynos:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 15 * * *'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Stop Heroku Dynos
        run: heroku ps:scale web=0 --app java-backend-coding-challenge
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
