name: Start Heroku Dynos

on:
  schedule:
    - cron: '0 9 * * 1-5'  # Encender a las 9 AM UTC de lunes a viernes

jobs:
  start-dynos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Start Heroku Dynos
        run: heroku ps:scale web=1 --app java-backend-coding-challenge
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
